[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"

[features]
seeds = false

[programs.localnet]
nft_staking = "89ChBjYeC4sM7GWRzvSoEZkDapFBiDNrxxT5PkM6uevN"

[programs.devnet]
nft_staking = "89ChBjYeC4sM7GWRzvSoEZkDapFBiDNrxxT5PkM6uevN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[test]
startup_wait = 100_000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
